// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZb7P39udQ5RN1DB5niFqbfhgR4gclaFg',
    appId: '1:738581457302:web:2c7eeb85cc1fd7d29415b7',
    messagingSenderId: '738581457302',
    projectId: 'ffff-af90e',
    authDomain: 'ffff-af90e.firebaseapp.com',
    storageBucket: 'ffff-af90e.appspot.com',
    measurementId: 'G-W14XLF30QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrNMYQz1Abmh11BixobKy8aJqGAnZij4',
    appId: '1:738581457302:android:500c04850b348e169415b7',
    messagingSenderId: '738581457302',
    projectId: 'ffff-af90e',
    storageBucket: 'ffff-af90e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYMh-oFSMd-TSutoK_uN4ZmSwkq98UTo',
    appId: '1:738581457302:ios:435a4f014d3aaa109415b7',
    messagingSenderId: '738581457302',
    projectId: 'ffff-af90e',
    storageBucket: 'ffff-af90e.appspot.com',
    iosBundleId: 'com.example.ffff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmYMh-oFSMd-TSutoK_uN4ZmSwkq98UTo',
    appId: '1:738581457302:ios:435a4f014d3aaa109415b7',
    messagingSenderId: '738581457302',
    projectId: 'ffff-af90e',
    storageBucket: 'ffff-af90e.appspot.com',
    iosBundleId: 'com.example.ffff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZb7P39udQ5RN1DB5niFqbfhgR4gclaFg',
    appId: '1:738581457302:web:d9ae614de592bc259415b7',
    messagingSenderId: '738581457302',
    projectId: 'ffff-af90e',
    authDomain: 'ffff-af90e.firebaseapp.com',
    storageBucket: 'ffff-af90e.appspot.com',
    measurementId: 'G-C8T3VH8HGV',
  );
}
